#!/bin/bash
# run the script with one command line argument, which represents the input file name
# $./Lab4_2script actor_movies_short.txt
# actor_movies_short.txt is the input file name as the command line argument
# First, ask the user to input two movie titles
#        if both movie titles are in the actor_movies_short.txt, continue;
#        otherwise, quit immediately
# Repeatedly display the main menu to let the user choose an option (enter Q or q to quit):
#                       if opiton is A (or a), print all the actors in either of the two movies;
#                       if option is C (or c), print all the common actors in both of the movies;
#                       if option is O (or o), print all the actors who are in one movie, but not in both.
#                       if opiton is Q (or q), quit the script
#                       if other option, display the message of invalid choice.

# Begin with checking whether the number of the command line arguments is exactly one

if [ $# -ne 1 ]
then
    echo "Warning: need exactly one command line argument."
    echo "Usage: $0 <inputfile_name>"
    exit 1
fi

# Ask the user to input two movie titles to search for
echo "Please input the first movie title:"
read movie1
echo "Please input the second movie title:"
read movie2
# Check if both movies are in the input file
# if either one is not, quit the script
# otherwise continue...
if [ `grep -c -i "$movie1" $1` -gt 0 ] && [ `grep -c -i "$movie2" $1` -gt 0 ]
then    
    echo "Your input matches these two movies: "
    grep -m 1 -i -o ";[^;]*$movie1[^;]*;" $1 | cut -d';' -f 2
    grep -m 1 -i -o ";[^;]*$movie2[^;]*;" $1 | cut -d';' -f 2
    echo "Both movies are in the database, please continue..."
    #create two sets for the actors in each movie respectively
    grep -i "$movie1" $1 | cut -f 1 -d';' > actors_in_movie1.txt
    grep -i "$movie2" $1 | cut -f 1 -d';' > actors_in_movie2.txt
else
    echo "Invalid movie title."
    exit 1
fi

# Ask the user to input the option for searching to begin with
#echo "Please input your menu option (enter Q or q to quit)"
#echo "A --to print all the actors in either of the two movies."
#echo "C --to print all the common actors in both of the movies."
#echo "O --to print all the actors who are in one movie, but not in both."
#read usr_option

# Your script should start here
# create a loop to repeatedly ask the user to input the option for searching until the user enters Q or q to quit
while [ $"option" != "Q" -o $"usr_option" != "q" ] 
	do
echo "Please input your menu option (enter Q or q to quit)"
echo "A --to print all the actors in either of two movies."
echo "C --to print all the common actors in both of the movies."
echo "O --to print all the actors who are in one movie, but not in both."
read option

	if [ "$option" == "A" -o "$option" == "a" ]; then
		echo "All the actors in either of the movies:"
		# sort the list and print out all the actors
		sort actors_in_movie1.txt actors_in_movie2.txt | uniq
	
	else if [ "$option" == "C" -o "$option" == "c" ]; then
		echo "Common actors in both of the movies:"
		#sort the list and print out common actors
		sort actors_in_movie1.txt actors_in_movie2.txt | uniq -d
	
	else if [ "$option" == "O" -o "$option" == "o" ]; then
		echo "Actors in only one of the movies:"
		#sort and print out actors appearing in only one ,ovie 
		sort actors_in_movie1.txt actors_in_movie2.txt | uniq -u
	
	else if [ "$option" = "Q" -o "$option" == "q" ]; then
		exit 0 
		#exit the program if q entered
	else
		echo "Invalid option."
				fi
			fi
		fi
	fi
					


done





















#delete the temporary files
echo "Delete all temporary files..."
rm actors_in*.txt
exit 0

